name: flutter_omath
description: "A New Version of already uploeded application OMath puzzle app"

publish_to: 'none' 

#v1.7 = inapp purchase and ads integration.
#1.8 = New game mode true and false
#1.9 = ads issue
#1.10 = bug fixes and performance improvement, ads removed
version: 1.10.0+10

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.7.2
  collection: ^1.19.1
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  in_app_purchase: ^3.2.3
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.5.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/
    
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
