name: flutter_omath
description: "This Ad free and Subscription free PRO version"

publish_to: 'none' 



version: 1.2.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.7.2
  collection: ^1.19.1
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  #in_app_purchase: ^3.2.3
  #google_mobile_ads: ^6.0.0
  shared_preferences: ^2.5.3
  audioplayers: ^6.1.0
  confetti: ^0.8.0
  google_fonts: ^7.0.2
  animate_do: ^4.2.0
  supabase_flutter: ^2.8.4
  share_plus: ^10.1.4
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^6.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
      - .env
      - assets/images/
      - assets/sounds/
      - assets/avatars/
    
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
